name: CI
on:
  push:
  pull_request:
    branches: [main]

jobs:
  cypressTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci --ignore-scripts

      - name: Check ESLint
        uses: Maggi64/eslint-plus-action@master
        with:
          issueSummaryOnlyOnEvent: true